- name: Check if k9s version is installed
  command: k9s version
  changed_when: false
  failed_when: false
  register: k9s_check

- block:

  - name: "Download k9s ({{ k9s_version }})"
    get_url:
      url: "{{ k9s_url }}"
      dest: /tmp/
      checksum: "{{ k9s_checksum }}"
      timeout: 20
      validate_certs: no
    become: no
    register: rx

  - name: "Create install directory {{ k9s_install_dir }}"
    become: yes
    file:
      path: "{{ k9s_install_dir }}"
      state: directory

  - name: Unpack
    become: yes
    unarchive:
      remote_src: yes
      src: "{{ rx.dest }}"
      dest: "{{ k9s_install_dir }}"

  - name: Create link
    become: yes
    file:
      src: "{{ k9s_install_dir }}/k9s"
      dest: '/usr/local/bin/k9s'
      state: link

  when: "(k9s_check.stdout is not defined) or (k9s_version not in k9s_check.stdout)"